In [11]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)

    cv2.rectangle(frame, (200,200),(25,25),(255,0,255),3)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)

    if prediction[0][0] > 0.5:
        print('Rock')
    elif prediction[0][1] >0.5:
        print("Paper")
    elif prediction[0][2] > 0.5:

        print("Scissors")

    else:
        print("Nothing")

    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 2s 2s/step
Paper
[[5.5308362e-09 9.9998212e-01 1.5413721e-05 2.5225738e-06]]
1/1 [==============================] - 0s 82ms/step
Paper
[[6.4550337e-10 9.9994183e-01 5.3465224e-05 4.6933437e-06]]
1/1 [==============================] - 0s 55ms/step
Paper
[[6.7205835e-10 9.9999440e-01 5.0404315e-06 5.7931112e-07]]
1/1 [==============================] - 0s 62ms/step
Paper
[[2.1896263e-09 9.9994481e-01 4.2620464e-05 1.2496216e-05]]
1/1 [==============================] - 0s 55ms/step
Paper
[[9.0770724e-10 9.9996531e-01 3.0882205e-05 3.8196176e-06]]
1/1 [==============================] - 0s 65ms/step
Paper
[[3.2927099e-09 9.9994302e-01 4.6864148e-05 1.0110196e-05]]
1/1 [==============================] - 0s 59ms/step
Paper
[[3.8588035e-09 9.9980623e-01 1.5765276e-04 3.6111396e-05]]
1/1 [==============================] - 0s 55ms/step
Paper
[[6.7701920e-11 9.9997175e-01 2.5387453e-05 2.8296545e-06]]
1/1 [==============================] - 0s 63ms/step
Paper
